In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Data/artwork_data.csv", low_memory = False)

In [3]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69201 entries, 0 to 69200
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  69201 non-null  int64
 1   accession_number    69201 non-null  object
 2   artist              69201 non-null  object
 3   artistRole          69201 non-null  object
 4   artistId            69201 non-null  int64
 5   title               69201 non-null  object
 6   dateText            69201 non-null  object
 7   medium              62817 non-null  object
 8   creditLine          69198 non-null  object
 9   year                63823 non-null  object
 10  acquisitionYear     69156 non-null  float64
 11  dimensions          66768 non-null  object
 12  width               65860 non-null  object
 13  height              65860 non-null  object
 14  depth               2514 non-null   float64
 15  units               65860 non-null  object
 16  inscription         6306 non-null   object
 17  thumbnailCopyright  14239 non-null  object
 18  thumbnailUrl        58415 non-null  object
 19  url                 69201 non-null  object
dtypes: float64(2), int64(2), object(16)
memory usage: 10.6+ MB

# 1) Stripping White Space

### check white space in `title` column

In [5]:
data.loc[data.title.str.contains("\s$", regex = True)]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
49498,4308,P07466,"Hamilton Finlay, Ian",artist,1093,Port-Distinguishing Letters of Scottish Fishin...,1976,Screenprint on ceramic tile,Purchased 1981,1976,1981.0,unconfirmed: 153 x 153 mm,153,153,NaN,mm,NaN,Â© Estate of Ian Hamilton Finlay,http://www.tate.org.uk/art/images/work/P/P07/P...,http://www.tate.org.uk/art/artworks/hamilton-f...
50534,2235,P11065,"Clarke, Brian",artist,911,Boys,1981,Screenprint on paper,Presented by Paul Beldock 1983,1981,1983.0,image: 1003 x 700 mm,1003,700,NaN,mm,date inscribed,Â© Brian Clarke. All Rights Reserved 2014 / DACS,http://www.tate.org.uk/art/images/work/P/P11/P...,http://www.tate.org.uk/art/artworks/clarke-boy...
50535,2236,P11066,"Clarke, Brian",artist,911,Buildings,1981,Screenprint on paper,Presented by Paul Beldock 1983,1981,1983.0,image: 1005 x 698 mm,1005,698,NaN,mm,date inscribed,Â© Brian Clarke. All Rights Reserved 2014 / DACS,http://www.tate.org.uk/art/images/work/P/P11/P...,http://www.tate.org.uk/art/artworks/clarke-bui...
50537,2238,P11068,"Clarke, Brian",artist,911,Pray for Josquin,1981,Screenprint on paper,Presented by Paul Beldock 1983,1981,1983.0,image: 1115 x 688 mm,1115,688,NaN,mm,date inscribed,Â© Brian Clarke. All Rights Reserved 2014 / DACS,http://www.tate.org.uk/art/images/work/P/P11/P...,http://www.tate.org.uk/art/artworks/clarke-pra...
53186,21168,P77679,"Bourgeois, Louise",artist,2351,Untitled (Safety Pins),1991,Drypoint on paper,Purchased 1994,1991,1994.0,image: 303 x 379 mm,303,379,NaN,mm,NaN,Â© The Easton Foundation,http://www.tate.org.uk/art/images/work/P/P77/P...,http://www.tate.org.uk/art/artworks/bourgeois-...
56283,5826,T00705,"Hamilton, Richard",artist,1244,Towards a definitive statement on the coming t...,1962,"Oil paint, cellulose paint and printed paper o...",Purchased 1964,1962,1964.0,support: 610 x 813 mm frame: 809 x 1011 x 810 mm,610,813,NaN,mm,date inscribed,Â© The estate of Richard Hamilton,http://www.tate.org.uk/art/images/work/T/T00/T...,http://www.tate.org.uk/art/artworks/hamilton-t...
67409,88191,T12064,"Leach, David",artist,7651,2 Standard Ware Mead Cups,1945â55,Ochre porcelain,Accepted by HM Government in lieu of inheritan...,1945,2005.0,object: 70 x 80 x 80 mm,70,80,80.0,mm,NaN,Â© The estate of Bernard Leach,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/leach-2-st...
67432,88215,T12087,"Leach, Bernard",artist,1478,Bowl,c.1960,Porcelain,Accepted by HM Government in lieu of inheritan...,1960,2005.0,object: 50 x 140 x 140 mm,50,140,140.0,mm,NaN,Â© The estate of Bernard Leach,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/leach-bowl...

## 1.1) white space stripping on entire column

In [6]:
data.title.str.strip()

0        A Figure Bowing before a Seated Old Man with h...
1        Two Drawings of Frightened Figures, Probably f...
2        The Preaching of Warning. Verso: An Old Man En...
3           Six Drawings of Figures with Outstretched Arms
4        The Circle of the Lustful: Francesca da Rimini...
                               ...
69196                          Larvae (from Tampax Romana)
69197                     Living Womb (from Tampax Romana)
69198                                        Present Tense
69199            Work No. 227: The lights going on and off
69200                     Dancing Scene in the West Indies
Name: title, Length: 69201, dtype: object

In [8]:
data.title = data.title.str.strip()

In [12]:
# confirm again
# now there is no rows with whitespace in title
data.loc[data.title.str.contains("\s$", regex = True)]

Empty DataFrame
Columns: [id, accession_number, artist, artistRole, artistId, title, dateText, medium, creditLine, year, acquisitionYear, dimensions, width, height, depth, units, inscription, thumbnailCopyright, thumbnailUrl, url]
Index: []

### other methods : `rstrip()` and `lstrip()`

## 1.2) Alternative approach: using `transform()`
- this method has more flexibility as we can do different operations using lambda

In [13]:
data.title.transform(lambda x : x.strip())

0        A Figure Bowing before a Seated Old Man with h...
1        Two Drawings of Frightened Figures, Probably f...
2        The Preaching of Warning. Verso: An Old Man En...
3           Six Drawings of Figures with Outstretched Arms
4        The Circle of the Lustful: Francesca da Rimini...
                               ...
69196                          Larvae (from Tampax Romana)
69197                     Living Womb (from Tampax Romana)
69198                                        Present Tense
69199            Work No. 227: The lights going on and off
69200                     Dancing Scene in the West Indies
Name: title, Length: 69201, dtype: object

-----------------

# 2) Replacing Bad data with NaN

In [14]:
data = pd.read_csv("Data/artwork_data.csv", low_memory = False)

In [15]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

## 2.1) replacing with NaN  using `replace` method, for `dateText` where `date not known`

### first check the the entire column for na values

In [16]:
pd.isna(data.loc[:, "dateText"])

0        False
1        False
2        False
3        False
4        False
         ...
69196    False
69197    False
69198    False
69199    False
69200    False
Name: dateText, Length: 69201, dtype: bool

### replacing with nan

In [18]:
from numpy import nan

In [20]:
data.replace({'dataText' : {'date not known' : nan}}, inplace = True)

In [21]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

## 2.2) replacing nan using `loc` method

In [23]:
data = pd.read_csv("Data/artwork_data.csv", low_memory = False)
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

In [26]:
data.loc[data.dateText == "date not known", ["dateText"]] = nan

In [27]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,NaN,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",NaN,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

----------

### check `year` data for bad data

In [29]:
# check year data which contains values but contains data other than digits too
data.loc[data.year.notnull() & data.year.str.contains("[^0-9]")]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
67968,99332,T12629,"Roberts, William",artist,1855,Families on a beach,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,support: 127 x 178 mm,127,178,NaN,mm,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-fa...
67980,99346,T12641,"Roberts, William",artist,1855,Peasants and horseman,no date,Graphite and watercolour on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,184 x 140 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-pe...
67987,99354,T12648,"Roberts, William",artist,1855,The Beatles,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,178 x 127 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-th...
67994,99361,T12655,"Roberts, William",artist,1855,The peasants,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,191 x 133 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-th...
68002,99370,T12663,"Roberts, William",artist,1855,Two ladies talking,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,178 x 127 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-tw...
68015,99384,T12676,"Roberts, William",artist,1855,Butcherâs Man,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,support: 267 x 191 mm,267,191,NaN,mm,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-bu...
68033,99407,T12694,"Roberts, William",artist,1855,Men fishing,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,203 x 172 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-me...
68042,99426,T12703,"Roberts, William",artist,1855,Bar scene,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,127 x 184 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-ba...
68047,99431,T12708,"Roberts, William",artist,1855,The critic intervenes; Man milking a goat (rev...,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,152 x 133 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-th...
68051,99435,T12712,"Roberts, William",artist,1855,Woman brushing anotherâs hair,no date,Watercolour and graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,178 x 89 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-wo...
68056,99440,T12717,"Roberts, William",artist,1855,Group of people in a field,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,187 x 133 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-gr...
68057,99441,T12718,"Roberts, William",artist,1855,Two women playing with a cat,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,1528 x 121 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-tw...
68062,99446,T12723,"Roberts, William",artist,1855,Group of people standing on a corner,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,184 x 133 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-gr...
68070,99454,T12731,"Roberts, William",artist,1855,Group of people in a punt,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,273 x 172 mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/roberts-gr...
68072,99456,T12733,"Roberts, William",artist,1855,Party scene,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,122 x 108 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-pa...
68074,99458,T12735,"Roberts, William",artist,1855,Lady in a hat,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,184 x 133 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-la...
68076,99460,T12737,"Roberts, William",artist,1855,The toast,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,178 x 121 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-th...
68077,99462,T12738,"Roberts, William",artist,1855,People diving into a swimming pool,no date,Graphite on paper,Accepted by HM Government in lieu of inheritan...,no date,2008.0,184 x 162 mm,NaN,NaN,NaN,NaN,NaN,Â© The estate of William Roberts,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/roberts-pe...
69165,121190,T13834,"Barlow, Phyllida",artist,10908,Untitled,c.1997â9,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,c.1997-9,2013.0,unconfirmed: 389 x 562 mm,389,562,NaN,mm,NaN,Â© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...

In [34]:
data.loc[data.year.notnull() & data.year.astype(str).str.contains("[^0-9]"), ["year"]] = nan

In [35]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035.0,A00001,"Blake, Robert",artist,38.0,A Figure Bowing before a Seated Old Man with h...,NaN,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036.0,A00002,"Blake, Robert",artist,38.0,"Two Drawings of Frightened Figures, Probably f...",NaN,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

--------------

# 3) Filling missing data with a value

In [36]:
data = pd.read_csv("Data/artwork_data.csv", low_memory = False)

In [37]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

In [38]:
data.fillna(0)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,0,1922.0,support: 394 x 419 mm,394,419,0.0,mm,0,0,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,0,1922.0,support: 311 x 213 mm,311,213,0.0,mm,0,0,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785,1922.0,support: 343 x 467 mm,343,467,0.0,mm,0,0,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,0,1922.0,support: 318 x 394 mm,318,394,0.0,mm,0,0,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,0.0,mm,0,0,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,0,0,0,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,0,0,0,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410,2990.0,mm,0,0,0,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,0,0,0.0,0,0,0,0,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764â96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660,0.0,mm,0,0,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

now we can see fillna() with 0 has filled every nan values across with 0, but we only want `depth` column for now.

## 3.1) fill nan value for specific column
- df.fillna(value = {"col_name": value})

In [40]:
data.fillna(value = {"depth": 0})

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785,1922.0,support: 343 x 467 mm,343,467,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,NaN,NaN,0.0,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764â96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [41]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

In [43]:
data.fillna(value = {"depth": 0}, inplace = True)

In [44]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,0.0,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

----------

# 4) Dropping rows of data

In [45]:
data = pd.read_csv("Data/artwork_data.csv", low_memory = False)
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

In [46]:
data.shape

(69201, 20)

### 4.1) drop nan values

In [47]:
data.dropna()

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
1738,98171,AR00001,"Katz, Alex",artist,1386,Pansies,1967,Oil paint on hardboard,ARTIST ROOMS Acquired jointly with the Nationa...,1967,2008.0,support: 309 x 404 x 4 mm frame: 322 x 424 x 3...,309,404,4.0,mm,date inscribed,Â© Alex Katz,http://www.tate.org.uk/art/images/work/AR/AR00...,http://www.tate.org.uk/art/artworks/katz-pansi...
1739,98172,AR00002,"Katz, Alex",artist,1386,Tulips,1969,Oil paint on hardboard,ARTIST ROOMS Acquired jointly with the Nationa...,1969,2008.0,support: 356 x 253 x 3 mm frame: 375 x 273 x 3...,356,253,3.0,mm,date inscribed,Â© Alex Katz,http://www.tate.org.uk/art/images/work/AR/AR00...,http://www.tate.org.uk/art/artworks/katz-tulip...
1740,98173,AR00003,"Katz, Alex",artist,1386,West Window,1979,Oil paint on hardboard,ARTIST ROOMS Acquired jointly with the Nationa...,1979,2008.0,support: 196 x 238 x 3 mm frame: 216 x 256 x 3...,196,238,3.0,mm,date inscribed,Â© Alex Katz,http://www.tate.org.uk/art/images/work/AR/AR00...,http://www.tate.org.uk/art/artworks/katz-west-...
1741,98174,AR00004,"Katz, Alex",artist,1386,Lillies Against Yellow House,1983,Oil paint on hardboard,ARTIST ROOMS Acquired jointly with the Nationa...,1983,2008.0,support: 307 x 229 x 3 mm frame: 327 x 249 x 3...,307,229,3.0,mm,date inscribed,Â© Alex Katz,http://www.tate.org.uk/art/images/work/AR/AR00...,http://www.tate.org.uk/art/artworks/katz-lilli...
1742,98175,AR00005,"Katz, Alex",artist,1386,Young Trees,1989,Oil paint on hardboard,ARTIST ROOMS Acquired jointly with the Nationa...,1989,2008.0,support: 407 x 301 x 3 mm frame: 426 x 320 x 3...,407,301,3.0,mm,date inscribed,Â© Alex Katz,http://www.tate.org.uk/art/images/work/AR/AR00...,http://www.tate.org.uk/art/artworks/katz-young...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61878,20155,T06453,"Buchheister, Carl",artist,2276,Composition Ursiem,1959,"Graphite, ink, oil paint and adhesive on paper...",Presented by Willi Kemp 1991,1959,1991.0,support: 302 x 389 x 23 mm,302,389,23.0,mm,date inscribed,"Â© DACS, 2014",http://www.tate.org.uk/art/images/work/T/T06/T...,http://www.tate.org.uk/art/artworks/buchheiste...
62083,20568,T06659,"Gober, Robert",artist,2309,Drains,1990,Pewter,Purchased 1992,1990,1992.0,object: 94 x 94 x 42 mm,94,94,42.0,mm,date inscribed,Â© Robert Gober,http://www.tate.org.uk/art/images/work/T/T06/T...,http://www.tate.org.uk/art/artworks/gober-drai...
62274,20984,T06858,"Paolozzi, Sir Eduardo",artist,1738,Cyclops,1957,Bronze,Purchased 1994,1957,1994.0,"object: 692 x 370 x 320 mm, 36.4 kg",692,370,320.0,mm,date inscribed,Â© The Eduardo Paolozzi Foundation,http://www.tate.org.uk/art/images/work/T/T06/T...,http://www.tate.org.uk/art/artworks/paolozzi-c...
62466,21517,T07052,"Irvin, Albert",artist,1342,St Germain,1995,Acrylic paint on canvas,Purchased 1996,1995,1996.0,support: 2140 x 3056 x 52 mm,2140,3056,52.0,mm,date inscribed,Â© Albert Irvin,http://www.tate.org.uk/art/images/work/T/T07/T...,http://www.tate.org.uk/art/artworks/irvin-st-g...
62596,21805,T07183,"Davey, Grenville",artist,2295,By Air,1989,"Hardboard, wood and steel",Presented by Janet Wolfson de Botton 1996,1989,1996.0,displayed: 1850 x 3250 x 1850 mm,1850,3250,1850.0,mm,date inscribed,Â© Grenville Davey,http://www.tate.org.uk/art/images/work/T/T07/T...,http://www.tate.org.uk/art/artworks/davey-by-a...

In [49]:
data.dropna().shape

(164, 20)

### 4.2) dropping rows only if all values of all columns are null
- useful at the final stage of data cleaning, after you converted all values to numerical

In [51]:
data.dropna(how = "all").shape

(69201, 20)

### 4.3) dropping rows using `threshold`

In [53]:
# drop the row only if 15 of columns values are null (out of data frame's 20 columns)
data.dropna(thresh = 15). shape

(66379, 20)

## 4.4) dropping rows based on specific column's values are NaN
- or
- and (using `how = all`)

In [56]:
#drop the rows only if year or acquisitionYear column values are NaN
data.dropna(subset = ["year", "acquisitionYear"]).shape

(63781, 20)

In [57]:
#drop the rows only if BOTH year and acquisitionYear column values are NaN
data.dropna(subset = ["year", "acquisitionYear"], how = "all").shape

(69198, 20)

In [58]:
data.dropna(subset = ["year", "acquisitionYear"], how = "all", inplace = True)

In [59]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

----------------

# 5) Identifying and Dropping Duplicate Data

In [60]:
data = pd.read_csv("Data/artwork_sample.csv")

In [61]:
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

### 5.1) dropping duplicates based on specific column

In [62]:
# now we try to drop duplicates based on "artist" column
data.drop_duplicates(subset = ["artist"])

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

now only two rows remains. This makes sense because there are only 2 distinct artist name.

### 5.2) keep first and keep last

In [63]:
data.drop_duplicates(subset = ["artist"], keep = "first")

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [64]:
data.drop_duplicates(subset = ["artist"], keep = "last")

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
9,1044,A00010,"Blake, William",artist,39,The Pit of Disease: The Falsifiers,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 340 mm,243,340,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

### 5.3) keep none if there is more than one duplicate for that value

In [66]:
data.drop_duplicates(subset = ["artist"], keep = False)
# this returns none because each of the artist has more than one rows

Empty DataFrame
Columns: [id, accession_number, artist, artistRole, artistId, title, dateText, medium, creditLine, year, acquisitionYear, dimensions, width, height, depth, units, inscription, thumbnailCopyright, thumbnailUrl, url]
Index: []

-------

In [67]:
data.drop_duplicates(subset = ["artist"], keep = "first")

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

-----------------

In [68]:
data = pd.read_csv("Data/artwork_data.csv", low_memory = False)
data.head(2)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

In [69]:
data.shape

(69201, 20)

## 5.5) checking which rows are duplicated

In [70]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
69196    False
69197    False
69198    False
69199    False
69200    False
Length: 69201, dtype: bool

In [71]:
data.loc[data.duplicated()]
# returns nothing because none of the rows are fully duplicated

Empty DataFrame
Columns: [id, accession_number, artist, artistRole, artistId, title, dateText, medium, creditLine, year, acquisitionYear, dimensions, width, height, depth, units, inscription, thumbnailCopyright, thumbnailUrl, url]
Index: []

In [75]:
# we set keep=False, because we want to IDENTIFY the duplicates on every rows (we don't want to exclude the first or last or keep it for now)
# otherwise duplicated() method will return false on each of those rows and this won't help much us to identify the duplicates.
data.duplicated(subset = ["artist", "title"], keep = False)

0        False
1        False
2        False
3        False
4         True
         ...
69196    False
69197    False
69198    False
69199    False
69200    False
Length: 69201, dtype: bool

In [78]:
data.loc[data.duplicated(subset = ["artist", "title"], keep = False)]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
5,1040,A00006,"Blake, William",artist,39,Ciampolo the Barrator Tormented by the Devils,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 240 x 338 mm,240,338,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-ciam...
6,1041,A00007,"Blake, William",artist,39,The Baffled Devils Fighting,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 242 x 334 mm,242,334,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
7,1042,A00008,"Blake, William",artist,39,The Six-Footed Serpent Attacking Agnolo Brunel...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 246 x 340 mm,246,340,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
8,1043,A00009,"Blake, William",artist,39,The Serpent Attacking Buoso Donati,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 241 x 335 mm,241,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69169,121194,T13838,"Barlow, Phyllida",artist,10908,Untitled,1999,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,1999,2013.0,unconfirmed: 637 x 897 mm,637,897,NaN,mm,NaN,Â© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69170,121195,T13839,"Barlow, Phyllida",artist,10908,Untitled,2003,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2003,2013.0,support: 560 x 762 mm,560,762,NaN,mm,NaN,Â© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69171,121196,T13840,"Barlow, Phyllida",artist,10908,Untitled,2003,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2003,2013.0,support: 558 x 760 mm,558,760,NaN,mm,NaN,Â© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69172,121197,T13841,"Barlow, Phyllida",artist,10908,Untitled,2004,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2004,2013.0,support: 380 x 566 mm,380,566,NaN,mm,NaN,Â© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69173,121198,T13842,"Barlow, Phyllida",artist,10908,Untitled,2006,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2006,2013.0,support: 560 x 762 mm,560,762,NaN,mm,NaN,Â© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...

### let's dig more details what are causing the above data as duplicates

In [79]:
data.loc[data.title.str.contains("The Circle of the Lustful")]
# as we can see the following as not really duplicate because if we can dateText, one is reprinted in 1892 and other is in 1968
# so it's up to us now how want want to handle those cases

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
57394,1156,T01950,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â7, reprinted 1968",Line-engraving on paper,Presented by Lessing J. Rosenwald 1975,1826,1975.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T01/T...,http://www.tate.org.uk/art/artworks/blake-the-...